spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
myapp:
  admin-username: admin@hodory.dev
  admin-password: admin@password
  user-username: user@hodory.dev
  user-password: user@password
  client-id: myApp
  client-secret: pass
